version: '3.8'

services:
  backend:
    image: my-backend-app:latest  # 빌드한 Docker 이미지 사용
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.26.4.40:3306/restfetch  # EC2의 MySQL IP 주소 및 포트
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Rnwheo1234!
      - SPRING_REDIS_HOST=172.26.4.40  # EC2의 Redis IP 주소
      - SPRING_REDIS_PORT=6379  # Redis 포트
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rnwheo1234!
      MYSQL_DATABASE: restfetch

  redis:
    image: redis:alpine
    restart: always
