version: '3.8'

services:
  backend:
    build:
      context: ./backend  # backend 폴더를 컨텍스트로 설정
      dockerfile: Dockerfile  # Dockerfile의 이름
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.26.4.40:3306/restfetch
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Rnwheo1234!
      - SPRING_REDIS_HOST=localhost
    depends_on:
      - db
      # - redis  # 필요시 주석 해제

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rnwheo1234!
      MYSQL_DATABASE: restfetch
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
