apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-backend-app
  template:
    metadata:
      labels:
        app: my-backend-app
    spec:
      containers:
        - name: my-backend-app
          image: my-backend-app:latest # Docker 이미지 이름
          ports:
            - containerPort: 8080 # 애플리케이션이 사용하는 포트
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001 # 외부에서 접근할 포트
  selector:
    app: my-backend-app
